#%RAML 1.0 Library

uses:
  domain: ../extensions/domain.raml

(domain.base): "http://acme-banking/vocabulary/quantities#"

usage: Structured types used in the domain description when a simple literal value cannot be used to capture the meaning.

annotationTypes:

  # Classes

  StructuredValue:
    displayName: Structured Value
    description: |
      Structured values are used when the value of a property has a more complex structure than simply being a textual
      value or a reference to another thing.
      (domain.inherits):
        - (domain.Class)
      (domain.literalProperties):
        - (value)

  RepaymentSpecification:
    displayName: Repayment Specification
    description: A structured value representing repayment.
    (domain.inherits):
      - (StructuredValue)
    (domain.literalProperties):
      - (loanPaymentFrequency)
      - (numberOfLoanPayments)
    (domain.objectProperties):
      - (downPayment)
      - (earlyPrepaymentPenalty)
      - (loanPaymentAmount)

  MonetaryAmount:
    displayName: Monetary Amount
    description: |
      A monetary value or range. This type can be used to describe an amount of money such as $50 USD, or a range as in
      describing a bank account being suitable for a balance between £1,000 and £1,000,000 GBP, or the value of a salary,
      etc.
    (domain.inherits):
      - (StructuredValue)
    (domain.literalProperties):
      - (currency)

  Duration:
    displayName: Duration
    description: Duration (use ISO 8601 duration format).


  # Properties

  value:
    displayName: value
    description: The value of the quantitative value or property value node.
    (domain.inherits):
      - (domain.LiteralProperty)
    (domain.range): any

  loanPaymentFrequency:
    displayName: loan payment frequency
    description: |
      Frequency of payments due, i.e. number of months between payments. This is defined as a frequency,
      i.e. the reciprocal of a period of time.
    (domain.inherits):
      - (domain.LiteralProperty)
    (domain.range): number

  numberOfLoanPayments:
    displayName: number of loan payments
    description: |
      The number of payments contractually required at origination to repay the loan. For monthly paying loans this is
      the number of months from the contractual first payment date to the maturity date.
    (domain.inherits):
      - (domain.LiteralProperty)
    (domain.range): number

  downPayment:
    displayName: down payment
    description: |
      a type of payment made in cash during the onset of the purchase of an expensive good/service.
      The payment typically represents only a percentage of the full purchase price.
    (domain.inherits): (domain.ObjectProperty)
    (domain.range): MonetaryAmount

  earlyPrepaymentPenalty:
    displayName: early penalty
    description: The amount to be paid as a penalty in the event of early payment of the loan.
    (domain.inherits): (domain.ObjectProperty)
    (domain.range): MonetaryAmount

  loanPaymentAmount:
    displayName: loan payment amount
    description: The amount of money to pay in a single payment.
    (domain.inherits): (domain.ObjectProperty)
    (domain.range): MonetaryAmount

  currency:
    displayName: currency
    description: The currency in which the monetary amount is expressed (in 3-letter ISO 4217 format).
    (domain.inherits): (domain.LiteralProperty)
    (domain.range): string


types:

  MonetaryAmountData:
    (domain.class): (MonetaryAmount)
    properties:
      value: number
      currency: string

  DurationData:
    (domain.class): (Duration)
    properties:
      value: string

  RepaymentSpecificationData:
    (domain.class): (RepaymentSpecification)
    properties:
      down_payment: MonetaryAmountData
      payment_frequency: number
      number_payments: integer
      payment_amount: MonetaryAmountData
      early_payment_penalty: MonetaryAmountData
